[package]
name = "rush"
version = "0.1.11"
edition = "2021"
license = "Unlicense"
description = "the rust shell"
repository = "https://github.com/parth/rush"

[dependencies]
crossterm = "0.27.0"
shell-words = "1.1.0"
