[package]
name = "rush"
version = "0.1.12"
edition = "2021"
license = "Unlicense"
description = "the rust shell"
repository = "https://github.com/parth/rush"

[dependencies]
anyhow = "1.0.81"
crossterm = "0.27.0"
